export type RequestOptions = { signal?: AbortSignal };
export type MutationOptions = RequestOptions & { idempotencyKey?: string };
export type WaitOptions = RequestOptions & { timeoutMs?: number };
export type ExecutionStatus = "queued" | "running" | "succeeded" | "failed" | "cancelled" | "timed_out" | "output_limit" | "lost";
export type Execution = { id: string; environment_id: string; status: ExecutionStatus; exit_code: number | null; cancel_requested: boolean; stdout_bytes: number; stderr_bytes: number; created_at: string; updated_at: string; artifacts: { path: string; size: number | null; error: string | null }[] };
export type ExecutionInput = { command: string; cwd?: string; timeout_seconds?: number; artifacts?: string[] };
export type Operation = { environment_id: string; operation_id: string; status: string };
export type ProjectConfiguration = {
  source_type?: "image" | "snapshot";
  image?: string | null;
  snapshot_id?: string | null;
  registry_id?: string | null;
  repository?: string | null;
  repository_branch?: string | null;
  setup_command?: string | null;
  initialization_command?: string | null;
  startup_command?: string | null;
  readiness_command?: string | null;
  cpu?: 1 | 2 | 4 | 8;
  memory_mb?: 1024 | 2048 | 4096 | 8192 | 16384;
  auto_stop_minutes?: number | null;
};
export type ProjectSetupInput = { name: string; configuration: ProjectConfiguration };
export type ProjectSetup = ProjectSetupInput & { id: string; created_at: string };
export type Prebuild = { id: string; template_id: string | null; snapshot_id: string | null; name: string; status: "building" | "ready" | "failed"; repository_revision: string | null; configuration: ProjectConfiguration; error_message: string | null; created_at: string; completed_at: string | null };
export type Environment = { id: string; name: string; state: string; [key: string]: unknown };
export type Snapshot = { id: string; name: string; status: string; [key: string]: unknown };
export type Output = { sequence: string; stream: "stdout" | "stderr"; byte_offset: number; data: string };
export type ExecutionEvent = ({ type: "output"; bytes: Uint8Array } & Output) | { type: "done"; execution: Execution };
export type EnvironmentInput = { prebuild_id?: string; source_type?: "image" | "snapshot"; image?: string; snapshot_id?: string; registry_id?: string; code_trust: "trusted" | "untrusted"; name?: string; cpu?: number; memory_mb?: number; preview_enabled?: boolean; auto_stop_minutes?: number | null; auto_delete_minutes?: number | null; environment_variables?: { name: string; value: string }[]; initialization_command?: string; startup_command?: string; readiness_command?: string; compute_node_id?: string; [key: string]: unknown };
export class DriftverkError extends Error { status: number; idempotencyKey?: string; }
export class Driftverk {
  constructor(options: { baseUrl: string; apiKey: string; fetch?: typeof fetch });
  listProjectSetups(options?: RequestOptions): Promise<ProjectSetup[]>;
  getProjectSetup(id: string, options?: RequestOptions): Promise<ProjectSetup>;
  createProjectSetup(input: ProjectSetupInput, options?: MutationOptions): Promise<ProjectSetup>;
  updateProjectSetup(id: string, input: ProjectSetupInput, options?: MutationOptions): Promise<ProjectSetup>;
  deleteProjectSetup(id: string, options?: MutationOptions): Promise<{ deleted: true }>;
  listPrebuilds(options?: RequestOptions): Promise<Prebuild[]>;
  getPrebuild(id: string, options?: RequestOptions): Promise<Prebuild>;
  buildPrebuild(input: { template_id: string; compute_node_id?: string }, options?: MutationOptions): Promise<{ id: string; status: "building" }>;
  waitForPrebuild(id: string, options?: WaitOptions): Promise<Prebuild>;
  createEnvironment(input: EnvironmentInput, options?: MutationOptions): Promise<Operation>;
  listEnvironments(options?: RequestOptions): Promise<Environment[]>;
  listSnapshots(options?: RequestOptions): Promise<Snapshot[]>;
  getEnvironment(id: string, options?: RequestOptions): Promise<Environment & { ssh_username: string; environment_variable_names: string[] }>;
  startEnvironment(id: string, options?: MutationOptions): Promise<Operation>;
  stopEnvironment(id: string, options?: MutationOptions): Promise<Operation>;
  createPreview(id: string, port: number, options?: RequestOptions): Promise<{ url: string; expires_at: string }>;
  getOperation(id: string, options?: RequestOptions): Promise<{ id: string; status: string; error_message: string | null; [key: string]: unknown }>;
  waitForOperation(id: string, options?: WaitOptions): ReturnType<Driftverk["getOperation"]>;
  deleteEnvironment(id: string, options?: MutationOptions): Promise<Operation>;
  execute(environmentId: string, input: ExecutionInput, options?: MutationOptions): Promise<{ id: string; environment_id: string; status: "queued" }>;
  getExecution(id: string, options?: RequestOptions): Promise<Execution>;
  waitForExecution(id: string, options?: WaitOptions): Promise<Execution>;
  readOutput(id: string, options?: RequestOptions & { after?: string }): Promise<Output[]>;
  events(id: string, options?: WaitOptions & { after?: string }): AsyncGenerator<ExecutionEvent>;
  artifact(id: string, path: string, options?: RequestOptions): Promise<Uint8Array>;
  cancelExecution(id: string, options?: RequestOptions): Promise<Execution>;
  deleteExecution(id: string, options?: RequestOptions): Promise<{ deleted: true }>;
}
